export enum Papel{
      DIRETOR="DIRETOR",
      DIRETOR_FOTOGRAFIA="DIRETOR DE FOTOGRAFIA",
      SONOPLASTA="SONOPLASTA",
      EDITOR="EDITOR",
      ROTEITISTA="ROTEIRISTA",
      EFEITOS_VISUAIS="EFEITOS VISUAIS"
}